addons:
  postgresql: "9.3"
  
env:
    - TARGET=PostreSQL ZONEMASTER_BACKEND_CONFIG_FILE=../zonemster-backend/share/travis_postgresql_backend_config.ini
    
language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

before_script:
    - cd ..
    - git clone https://github.com/dotse/zonemaster-backend.git
    - cd zonemaster-backend
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .
    - if [[ "$TARGET" == "PostreSQL" ]]; then psql -c "create user travis_zonemaster WITH PASSWORD 'travis_zonemaster';" -U postgres; fi
    - if [[ "$TARGET" == "PostreSQL" ]]; then psql -c 'create database travis_zonemaster OWNER travis_zonemaster;' -U postgres; fi
    - if [[ "$TARGET" == "PostreSQL" ]]; then cpanm DBD::Pg; fi
    - if [[ "$TARGET" == "PostreSQL" ]]; then perl -I./lib ./script/create_db_postgresql_9.3.pl; fi
    
script:
    - perl Malefile.PL && make test
